modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
IssueTrackerURL="https://github.com/GhostgamesDHG/MinetopiaMod/issues"
[[mods]]
modId="gmm"
version="1.7"
displayName="MineTopia Mod"
updateJSONURL="https://raw.githubusercontent.com/GhostgamesDHG/update.json/main/update.json"
logoFile="logo.png"
authors="ArmedEndmion"
description='''
         This mod adds almost everything from the MineTopia world!
'''